"use client";

import { useEffect, useMemo, useRef, useState, useTransition } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { CalendarDays, Clock3, Lock, Users, Video, X } from "lucide-react";
import { enrollInEvent } from "@/app/events/actions";
import { AppShell } from "@/components/layout/AppShell";

export type EventRecord = { id: string; title: string; description: string | null; hostName: string; startsAt: string; endsAt: string | null; minTier: number; status: "upcoming" | "live" | "completed" | "cancelled"; enrolled: boolean; publishAt?: string | null; publishedAt?: string | null; cancelledAt?: string | null; cancellationReason?: string | null };
const formatter = new Intl.DateTimeFormat(undefined, { weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" });
const label = (tier: number) => tier === 5 ? "Masters" : `Tier ${tier}+`;
const state = (event: EventRecord, now: number) => event.status === "cancelled" ? "cancelled" : event.endsAt && new Date(event.endsAt).getTime() <= now ? "completed" : new Date(event.startsAt).getTime() <= now ? "live" : "upcoming";
const duration = (event: EventRecord) => event.endsAt ? `${Math.round((new Date(event.endsAt).getTime() - new Date(event.startsAt).getTime()) / 60_000)} min` : "Duration unavailable";

export function EventsView({ events, enrollmentAvailable, currentTier, isMaster, memberName, routeBase = "" }: { events: EventRecord[]; enrollmentAvailable: boolean; currentTier: number; isMaster: boolean; memberName?: string; routeBase?: string }) {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const [now, setNow] = useState(Date.now()); const [message, setMessage] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  useEffect(() => { const interval = window.setInterval(() => setNow(Date.now()), 30_000); return () => window.clearInterval(interval); }, []);
  const selected = useMemo(() => events.find((event) => event.id === params.get("event")) ?? null, [events, params]);
  const setSelected = (event: EventRecord | null) => { const next = new URLSearchParams(params); if (event) next.set("event", event.id); else next.delete("event"); router.replace(`${pathname}${next.size ? `?${next}` : ""}`, { scroll: false }); };
  const enroll = (id: string) => startTransition(async () => { const result = await enrollInEvent(id); setMessage(result.error ?? "You’re enrolled. Your event desk is ready."); });
  const upcoming = events.filter((event) => ["upcoming", "live"].includes(state(event, now)));
  const recent = events.filter((event) => state(event, now) === "completed" && new Date(event.endsAt ?? event.startsAt).getTime() > now - 86_400_000);
  return <AppShell active="Events" title="Events Directory" isMaster={isMaster} currentTier={currentTier} memberName={memberName} routeBase={routeBase}><main className="mx-auto max-w-7xl p-4 md:p-8"><header className="mb-6 border-b border-surgical-steel pb-6"><p className="font-label text-xs tracking-[.14em] text-primary-container">SESSION LEDGER</p><h1 className="mt-2 font-headline text-2xl font-bold text-white md:text-3xl">Scheduled practice, held live.</h1><p className="mt-2 font-body text-sm text-on-surface-variant">Open a session to review its details, then enroll once to keep your place.</p></header>{message && <div role="status" className="mb-5 border border-primary-container/50 bg-primary-container/10 p-3 text-sm text-white">{message}</div>}{!enrollmentAvailable && <div role="status" className="mb-5 border border-amber-400/50 p-3 text-sm text-white">Enrollment is being prepared.</div>}<EventList title="On the schedule" events={upcoming} onOpen={setSelected} />{recent.length > 0 && <EventList title="Recently concluded" events={recent} onOpen={setSelected} />}</main>{selected && <MemberEventDetails event={selected} currentTier={currentTier} isMaster={isMaster} pending={pending} enrollmentAvailable={enrollmentAvailable} onClose={() => setSelected(null)} onEnroll={enroll} />}</AppShell>;
}
function EventList({ title, events, onOpen }: { title: string; events: EventRecord[]; onOpen: (event: EventRecord) => void }) { return <section className="mb-8"><div className="mb-3 flex gap-3"><h2 className="font-headline text-lg text-white">{title}</h2><span className="mt-4 h-px flex-1 bg-surgical-steel" /></div>{events.length ? <div className="grid gap-4 lg:grid-cols-2">{events.map((event) => <button type="button" key={event.id} onClick={() => onOpen(event)} className="rounded-lg border border-surgical-steel bg-monolith-surface p-5 text-left hover:border-primary-container"><div className="flex justify-between"><span className="font-label text-xs text-primary-container">{label(event.minTier)}</span><span className="font-label text-xs text-fog-muted">{event.status.toUpperCase()}</span></div><h3 className="mt-3 font-headline text-xl text-white">{event.title}</h3><p className="mt-2 text-sm text-on-surface-variant">{formatter.format(new Date(event.startsAt))}</p></button>)}</div> : <p className="border border-dashed border-surgical-steel p-6 text-sm text-fog-muted">No sessions in this window.</p>}</section>; }
function MemberEventDetails({ event, currentTier, isMaster, pending, enrollmentAvailable, onClose, onEnroll }: { event: EventRecord; currentTier: number; isMaster: boolean; pending: boolean; enrollmentAvailable: boolean; onClose: () => void; onEnroll: (id: string) => void }) { const close = useRef<HTMLButtonElement>(null); useEffect(() => { close.current?.focus(); const key = (e: KeyboardEvent) => e.key === "Escape" && onClose(); window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [onClose]); const permitted = isMaster || currentTier >= event.minTier; const live = state(event, Date.now()) === "live"; const join = async () => { const response = await fetch(`/api/events/${event.id}/room`); const payload = await response.json() as { url?: string; error?: string }; if (!response.ok || !payload.url) return window.alert(payload.error ?? "Room unavailable."); window.open(payload.url, "_blank", "noopener,noreferrer"); }; return <div role="dialog" aria-modal="true" aria-labelledby="member-event-title" className="fixed inset-0 z-50 grid place-items-center bg-surface-container-lowest/85 p-4" onMouseDown={onClose}><div onMouseDown={(e) => e.stopPropagation()} className="w-full max-w-lg rounded-lg border border-surgical-steel bg-monolith-surface"><div className="flex justify-between border-b border-surgical-steel p-5"><div><p className="font-label text-xs text-primary-container">EVENT DETAILS</p><h2 id="member-event-title" className="mt-1 font-headline text-xl text-white">{event.title}</h2></div><button ref={close} onClick={onClose}><X /></button></div><div className="space-y-4 p-5 text-sm"><p className="text-on-surface-variant">{event.description || "A focused live session for the Stoicverse community."}</p><div className="grid gap-2 border-y border-surgical-steel py-4 text-fog-muted"><p><CalendarDays className="mr-2 inline text-primary-container" size={14} />{formatter.format(new Date(event.startsAt))}</p><p><Clock3 className="mr-2 inline text-primary-container" size={14} />{duration(event)}</p><p><Users className="mr-2 inline text-primary-container" size={14} />Hosted by {event.hostName} · {label(event.minTier)}</p></div>{!permitted ? <p className="flex items-center gap-2 text-fog-muted"><Lock size={15} />Reach {label(event.minTier)} to enroll.</p> : !event.enrolled ? <button disabled={pending || !enrollmentAvailable} onClick={() => onEnroll(event.id)} className="w-full rounded-full bg-primary-container p-3 font-label text-xs text-on-primary-fixed">Enroll in session</button> : live ? <button onClick={join} className="flex w-full items-center justify-center gap-2 rounded-full bg-primary-container p-3 font-label text-xs text-on-primary-fixed"><Video size={15} />Join Zoom room</button> : <p className="text-fog-muted">You’re enrolled. The room opens at the scheduled time.</p>}</div></div></div>; }
