"use client";

import { useState, useTransition } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { deleteTier, saveTier } from "@/app/creator/tiers/actions";

export type ManagedTier = { id: string; level: number; title: string; description: string | null; required_lesson_count: number; courseCount: number };

export function CreatorTierManager({ tiers, memberName }: { tiers: ManagedTier[]; memberName: string }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null);
  const run = (data: FormData) => startTransition(async () => { const result = await saveTier(data); setMessage(result.error ?? "Tier saved."); });
  return <AppShell active="Tiers" title="Learning tiers" memberName={memberName} platformRole="influencer" routeBase="/creator"><main className="mx-auto max-w-5xl space-y-6 px-4 py-8 md:px-8"><header><p className="font-label text-xs uppercase tracking-[.16em] text-primary-container">Learning rules</p><h1 className="mt-2 font-headline text-3xl font-bold text-white">Tier progression</h1><p className="mt-2 text-sm text-on-surface-variant">Each tier controls access to courses. Completing courses can grant the next tier; progress is retained across membership lapses.</p></header>{message && <p role="status" className="border border-surgical-steel p-3 text-sm text-on-surface-variant">{message}</p>}<section className="grid gap-4">{tiers.map((tier) => <form key={tier.id} action={run} className="grid gap-3 border border-surgical-steel bg-monolith-surface p-4 md:grid-cols-[6rem_1fr_10rem_auto]"><input type="number" name="level" min="1" max="4" defaultValue={tier.level} className="bg-surface p-2 text-white"/><div><input name="title" defaultValue={tier.title} className="w-full bg-surface p-2 text-white"/><input name="description" defaultValue={tier.description ?? ""} placeholder="Description" className="mt-2 w-full bg-surface p-2 text-white"/><p className="mt-2 text-xs text-fog-muted">{tier.courseCount} mapped course{tier.courseCount === 1 ? "" : "s"}</p></div><input type="number" name="requiredLessonCount" min="1" defaultValue={tier.required_lesson_count} className="bg-surface p-2 text-white"/><div className="flex gap-2"><button disabled={pending} className="bg-primary-container px-3 text-xs font-bold text-on-primary-fixed">Save</button><button type="button" disabled={pending} onClick={() => startTransition(async () => { const result = await deleteTier(tier.id); setMessage(result.error ?? "Tier deleted."); })} className="border border-red-500 px-3 text-xs text-red-400">Delete</button></div></form>)}</section><form action={run} className="grid gap-3 border border-dashed border-surgical-steel p-4 md:grid-cols-4"><input name="level" type="number" min="1" max="4" placeholder="Level" className="bg-surface p-2 text-white"/><input name="title" placeholder="Tier title" className="bg-surface p-2 text-white"/><input name="requiredLessonCount" type="number" min="1" placeholder="Required lessons" className="bg-surface p-2 text-white"/><button disabled={pending} className="bg-primary-container px-3 text-xs font-bold text-on-primary-fixed">Add tier</button><input name="description" placeholder="Description" className="bg-surface p-2 text-white md:col-span-4"/></form></main></AppShell>;
}
