"use client";

import { useRouter } from "next/navigation";
import { CalendarDays, ChevronDown, FileText, FolderKanban, Gavel, GraduationCap, Plus, ShieldCheck, Users, type LucideIcon } from "lucide-react";
import { deleteChannel, deleteLesson, saveChannel, saveEvent, saveLesson, setModerator, updateReview } from "@/app/creator/actions";
import { createClient } from "@/lib/supabase/client";

type Channel = { id: string; name: string; type: string; description: string | null; min_tier: number; sort_order: number; is_active: boolean };
type Tier = { id: string; level: number; title: string };
type Lesson = { id: string; title: string; description: string | null; tier_id: string; duration_seconds: number; sort_order: number; status: string; release_at: string | null; tiers: { level: number; title: string }[] | null };
type Moderator = { id: string; full_name: string; platform_role: string };
type Review = { id: string; status: string; answers: unknown; submitted_at: string; decision_notes: string | null; call_scheduled_at: string | null; profiles: { full_name: string }[] | null };
type Event = { id: string; channel_id: string; title: string; description: string | null; starts_at: string; ends_at: string | null; min_tier: number; status: string };

const field = "mt-1 w-full border border-surgical-steel bg-surface-container-low px-3 py-2 font-body text-sm text-white outline-none focus:border-primary-container";
const button = "inline-flex min-h-10 items-center justify-center gap-2 border border-primary-container bg-primary-container px-4 font-label text-xs font-semibold uppercase tracking-wider text-on-primary-fixed transition hover:brightness-110 disabled:opacity-60";
const minor = "inline-flex min-h-9 items-center justify-center border border-surgical-steel px-3 font-label text-[11px] uppercase tracking-wider text-on-surface-variant hover:border-primary-container hover:text-primary-container";

function Section({ title, icon: Icon, children }: { title: string; icon: typeof Users; children: React.ReactNode }) {
  return <section className="border border-surgical-steel bg-monolith-surface"><header className="flex items-center gap-2 border-b border-surgical-steel bg-surface-container-low px-4 py-3"><Icon size={16} className="text-primary-container" /><h2 className="font-label text-xs uppercase tracking-[0.16em] text-white">{title}</h2></header>{children}</section>;
}

function Submit({ children }: { children: React.ReactNode }) { return <button className={button}>{children}</button>; }
function SignOutButton() {
  const router = useRouter();
  return <button className={minor} type="button" onClick={async () => { await createClient().auth.signOut(); router.replace("/"); router.refresh(); }}>Sign out</button>;
}

export function CreatorWorkspace({ activeMembers, channels, tiers, lessons, moderators, reviews, events }: { activeMembers: number; channels: Channel[]; tiers: Tier[]; lessons: Lesson[]; moderators: Moderator[]; reviews: Review[]; events: Event[] }) {
  const eventChannel = channels.find((channel) => channel.type === "events") ?? channels[0];
  const metrics: Array<{ label: string; value: number; Icon: LucideIcon }> = [
    { label: "Active members", value: activeMembers, Icon: Users },
    { label: "Courses & lessons", value: lessons.length, Icon: GraduationCap },
    { label: "Moderator cadre", value: moderators.length, Icon: ShieldCheck },
    { label: "Pending reviews", value: reviews.filter((review) => review.status === "pending").length, Icon: FileText },
  ];
  return <main className="min-h-screen bg-surface-container-lowest text-on-surface"><header className="sticky top-0 z-20 flex min-h-16 items-center justify-between border-b border-surgical-steel bg-surface px-4 md:px-8"><div><p className="font-label text-[10px] uppercase tracking-[0.18em] text-primary-container">Restricted operating surface</p><h1 className="font-headline text-xl font-semibold text-white">Influencer Workspace</h1></div><SignOutButton /></header><div className="mx-auto grid max-w-7xl gap-4 p-4 md:p-8">
    <div className="grid gap-px border border-surgical-steel bg-surgical-steel sm:grid-cols-2 lg:grid-cols-4">{metrics.map(({ label, value, Icon }) => <div key={label} className="bg-monolith-surface p-5"><div className="flex items-center justify-between text-fog-muted"><span className="font-label text-[11px] uppercase tracking-wider">{label}</span><Icon size={15} /></div><p className="mt-3 font-headline text-3xl text-primary-container">{value}</p></div>)}</div>
    <div className="grid gap-4 xl:grid-cols-2"><Section title="Course directory" icon={GraduationCap}><div className="divide-y divide-surgical-steel">{lessons.map((lesson) => <details key={lesson.id} className="group"><summary className="flex cursor-pointer items-center justify-between gap-3 p-4 list-none"><div><p className="font-body text-sm font-semibold text-white">{lesson.title}</p><p className="mt-1 font-label text-[10px] uppercase text-fog-muted">Tier {lesson.tiers?.[0]?.level ?? "?"} · {lesson.status} · order {lesson.sort_order}</p></div><ChevronDown size={16} className="text-fog-muted group-open:rotate-180" /></summary><LessonForm lesson={lesson} tiers={tiers} /></details>)}</div><details className="border-t border-surgical-steel"><summary className="cursor-pointer p-4 font-label text-xs uppercase text-primary-container"><Plus size={14} className="mr-2 inline" />New lesson</summary><LessonForm tiers={tiers} /></details></Section>
    <Section title="Channel controls" icon={FolderKanban}><div className="divide-y divide-surgical-steel">{channels.map((channel) => <details key={channel.id} className="group"><summary className="flex cursor-pointer items-center justify-between p-4 list-none"><div><p className="font-body text-sm font-semibold text-white">#{channel.name}</p><p className="mt-1 font-label text-[10px] uppercase text-fog-muted">{channel.type} · tier {channel.min_tier} · {channel.is_active ? "active" : "inactive"}</p></div><ChevronDown size={16} className="text-fog-muted group-open:rotate-180" /></summary><ChannelForm channel={channel} /></details>)}</div><details className="border-t border-surgical-steel"><summary className="cursor-pointer p-4 font-label text-xs uppercase text-primary-container"><Plus size={14} className="mr-2 inline" />New channel</summary><ChannelForm /></details></Section>
    <Section title="Moderator cadre" icon={Gavel}><div className="divide-y divide-surgical-steel">{moderators.map((moderator) => <div key={moderator.id} className="flex items-center justify-between gap-3 p-4"><div><p className="font-body text-sm font-semibold text-white">{moderator.full_name}</p><p className="font-label text-[10px] uppercase text-fog-muted">Moderator</p></div><form action={setModerator}><input type="hidden" name="userId" value={moderator.id} /><input type="hidden" name="role" value="member" /><Submit>Remove</Submit></form></div>)}{!moderators.length && <p className="p-4 font-body text-sm text-fog-muted">No moderators assigned.</p>}</div><p className="border-t border-surgical-steel p-4 font-body text-xs text-fog-muted">Assigning a member requires their profile ID; only member and moderator roles can be changed.</p><form action={setModerator} className="grid gap-3 border-t border-surgical-steel p-4 sm:grid-cols-[1fr_auto]"><input className={field} name="userId" placeholder="Member profile UUID" required /><input type="hidden" name="role" value="moderator" /><Submit>Assign moderator</Submit></form></Section>
    <Section title="Review queue" icon={FileText}><div className="divide-y divide-surgical-steel">{reviews.map((review) => <details key={review.id} className="group"><summary className="flex cursor-pointer items-center justify-between gap-3 p-4 list-none"><div><p className="font-body text-sm font-semibold text-white">{review.profiles?.[0]?.full_name ?? "Applicant"}</p><p className="mt-1 font-label text-[10px] uppercase text-fog-muted">{review.status} · {new Date(review.submitted_at).toLocaleDateString()}</p></div><ChevronDown size={16} className="text-fog-muted group-open:rotate-180" /></summary><form action={updateReview} className="grid gap-3 border-t border-surgical-steel p-4"><input type="hidden" name="id" value={review.id} /><label className="font-label text-[10px] uppercase text-fog-muted">Decision<select className={field} name="status" defaultValue={review.status}>{["under_review", "accepted", "rejected", "scheduled", "completed", "approved_for_team"].map((value) => <option key={value}>{value}</option>)}</select></label><textarea className={field} name="decisionNotes" defaultValue={review.decision_notes ?? ""} placeholder="Decision notes" /><input className={field} type="datetime-local" name="callScheduledAt" defaultValue={review.call_scheduled_at?.slice(0, 16)} /><input className={field} type="url" name="zoomUrl" placeholder="Secure call URL" /><Submit>Save review</Submit></form></details>)}{!reviews.length && <p className="p-4 font-body text-sm text-fog-muted">No review applications yet.</p>}</div></Section>
    <Section title="Event operations" icon={CalendarDays}><div className="divide-y divide-surgical-steel">{events.map((event) => <details key={event.id} className="group"><summary className="flex cursor-pointer items-center justify-between gap-3 p-4 list-none"><div><p className="font-body text-sm font-semibold text-white">{event.title}</p><p className="mt-1 font-label text-[10px] uppercase text-fog-muted">{event.status} · tier {event.min_tier} · {new Date(event.starts_at).toLocaleString()}</p></div><ChevronDown size={16} className="text-fog-muted group-open:rotate-180" /></summary><EventForm event={event} channelId={event.channel_id} /></details>)}</div>{eventChannel ? <details className="border-t border-surgical-steel"><summary className="cursor-pointer p-4 font-label text-xs uppercase text-primary-container"><Plus size={14} className="mr-2 inline" />New event</summary><EventForm channelId={eventChannel.id} /></details> : <p className="p-4 font-body text-sm text-error">Create an active events channel before creating events.</p>}</Section>
  </div></div></main>;
}

function ChannelForm({ channel }: { channel?: Channel }) { return <form action={saveChannel} className="grid gap-3 border-t border-surgical-steel p-4"><input type="hidden" name="id" value={channel?.id} /><div className="grid gap-3 sm:grid-cols-2"><input className={field} name="name" defaultValue={channel?.name} placeholder="channel-name" required /><select className={field} name="type" defaultValue={channel?.type ?? "text"}>{["text", "announcements", "events", "master"].map((type) => <option key={type}>{type}</option>)}</select><input className={field} name="minTier" type="number" min="1" max="5" defaultValue={channel?.min_tier ?? 1} required /><input className={field} name="sortOrder" type="number" min="0" defaultValue={channel?.sort_order ?? 0} required /></div><textarea className={field} name="description" defaultValue={channel?.description ?? ""} placeholder="Description" /><label className="font-body text-xs text-fog-muted"><input name="isActive" type="checkbox" defaultChecked={channel?.is_active ?? true} className="mr-2" />Active</label><div className="flex gap-3"><Submit>Save channel</Submit>{channel && <button formAction={deleteChannel} className={minor}>Delete</button>}</div></form>; }
function LessonForm({ lesson, tiers }: { lesson?: Lesson; tiers: Tier[] }) { return <form action={saveLesson} className="grid gap-3 border-t border-surgical-steel p-4"><input type="hidden" name="id" value={lesson?.id} /><div className="grid gap-3 sm:grid-cols-2"><input className={field} name="title" defaultValue={lesson?.title} placeholder="Lesson title" required /><select className={field} name="tierId" defaultValue={lesson?.tier_id}>{tiers.map((tier) => <option key={tier.id} value={tier.id}>Tier {tier.level}: {tier.title}</option>)}</select><input className={field} name="videoFileId" placeholder={lesson ? "Replace Google Drive file ID (optional)" : "Google Drive file ID"} required={!lesson} /><input className={field} name="durationSeconds" type="number" min="0" defaultValue={lesson?.duration_seconds ?? 0} required /><input className={field} name="sortOrder" type="number" min="0" defaultValue={lesson?.sort_order ?? 0} required /><select className={field} name="status" defaultValue={lesson?.status ?? "draft"}>{["draft", "published", "archived"].map((status) => <option key={status}>{status}</option>)}</select></div><textarea className={field} name="description" defaultValue={lesson?.description ?? ""} placeholder="Description" /><input className={field} type="datetime-local" name="releaseAt" defaultValue={lesson?.release_at?.slice(0, 16)} /><div className="flex gap-3"><Submit>Save lesson</Submit>{lesson && <button formAction={deleteLesson} className={minor}>Delete</button>}</div></form>; }
function EventForm({ event, channelId }: { event?: Event; channelId: string }) { return <form action={saveEvent} className="grid gap-3 border-t border-surgical-steel p-4"><input type="hidden" name="id" value={event?.id} /><input type="hidden" name="channelId" value={channelId} /><input className={field} name="title" defaultValue={event?.title} placeholder="Event title" required /><textarea className={field} name="description" defaultValue={event?.description ?? ""} placeholder="Description" /><div className="grid gap-3 sm:grid-cols-2"><input className={field} type="datetime-local" name="startsAt" defaultValue={event?.starts_at?.slice(0, 16)} required /><input className={field} type="datetime-local" name="endsAt" defaultValue={event?.ends_at?.slice(0, 16)} /><input className={field} name="minTier" type="number" min="1" max="5" defaultValue={event?.min_tier ?? 1} required /><select className={field} name="status" defaultValue={event?.status ?? "upcoming"}>{["upcoming", "live", "completed", "cancelled"].map((status) => <option key={status}>{status}</option>)}</select></div><input className={field} type="url" name="zoomUrl" placeholder="New HTTPS Zoom URL (leave blank to retain)" /><Submit>Save event</Submit></form>; }
