"use client";

import Link from 'next/link';
import { useEffect, useId, useMemo, useState, type ReactNode } from 'react';
import { ArrowDownToLine, ArrowRight, BarChart3, BookOpen, CalendarDays, Check, ChevronLeft, ChevronRight, CircleHelp, RefreshCw, Search, SlidersHorizontal, Users } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AppShell } from '@/components/layout/AppShell';
import { csvText, defaultFilters, parseFilters, type AnalyticsFilters, type AnalyticsReport } from '@/lib/analytics/model';

const tabs = ['overview', 'trading', 'courses', 'events', 'referrals'] as const;
type Tab = typeof tabs[number];
const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(n);
const number = (n: number) => new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(n);
const date = (s: string) => s ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(s)) : '—';
const delta = (n: number, p: number) => p === 0 ? n === 0 ? 'No change' : 'New this period' : `${n >= p ? '+' : ''}${number((n - p) / p * 100)}% vs previous period`;
const input = 'focus-ring min-h-11 w-full rounded-lg border border-surgical-steel bg-surface-container-lowest px-3 text-sm text-on-surface';
const button = 'focus-ring inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-surgical-steel px-4 text-sm font-semibold text-on-surface transition hover:border-primary-container disabled:opacity-40';

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid min-w-0 gap-2 text-xs font-medium text-fog-muted">{label}{children}</label>; }
function Note({ children }: { children: ReactNode }) { return <div className="flex items-start gap-3 rounded-xl bg-surface-container-low px-4 py-3 text-sm leading-6 text-on-surface-variant"><CircleHelp size={17} className="mt-1 shrink-0 text-primary-container" /><div>{children}</div></div>; }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="min-w-0 py-5 sm:px-5"><p className="text-sm text-on-surface-variant">{label}</p><p className="mt-2 break-words font-mono text-2xl font-semibold tabular-nums tracking-tight text-text-strong xl:text-3xl">{value}</p><p className="mt-2 text-xs leading-5 text-fog-muted">{detail}</p></div>; }
function Section({ title, description, children, action }: { title: string; description?: string; children: ReactNode; action?: ReactNode }) { return <section className="min-w-0"><div className="mb-5 flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-headline text-lg font-semibold text-text-strong">{title}</h2>{description && <p className="mt-1 max-w-[70ch] text-sm leading-6 text-fog-muted">{description}</p>}</div>{action}</div>{children}</section>; }

type Cell = string | number | null;
type TableRow = { id: string; cells: Cell[]; detail?: ReactNode };
function ReportTable({ title, headers, rows, numeric = [], filename }: { title: string; headers: string[]; rows: TableRow[]; numeric?: number[]; filename: string }) {
  const [sort, setSort] = useState<{ index: number; ascending: boolean } | null>(null);
  const [page, setPage] = useState(0);
  const sorted = useMemo(() => sort ? [...rows].sort((a, b) => {
    const av = a.cells[sort.index], bv = b.cells[sort.index];
    if (av === null) return bv === null ? 0 : 1;
    if (bv === null) return -1;
    const comparison = typeof av === 'number' && typeof bv === 'number' ? av - bv : String(av).localeCompare(String(bv));
    return (sort.ascending ? comparison : -comparison) || a.id.localeCompare(b.id);
  }) : rows, [rows, sort]);
  const pages = Math.max(1, Math.ceil(rows.length / 10)), current = Math.min(page, pages - 1);
  const exportRows = () => {
    const url = URL.createObjectURL(new Blob([csvText(headers, sorted.map(r => r.cells))], { type: 'text/csv;charset=utf-8;' }));
    const a = document.createElement('a'); a.href = url; a.download = `${filename}.csv`; a.click(); URL.revokeObjectURL(url);
  };
  return <div className="overflow-hidden rounded-xl border border-surgical-steel">
    <div className="flex items-center justify-between gap-3 border-b border-surgical-steel bg-surface-container-low px-4 py-3"><p aria-live="polite" className="text-xs text-fog-muted">{number(rows.length)} {rows.length === 1 ? 'result' : 'results'} · click a column to sort</p><button className={button} onClick={exportRows} disabled={!rows.length} aria-label={`Export ${title} as CSV`}><ArrowDownToLine size={15} /><span>Export CSV</span></button></div>
    {rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><caption className="sr-only">{title}</caption><thead className="bg-surface-container-lowest"><tr>{headers.map((h, i) => <th key={h} scope="col" aria-sort={sort?.index === i ? sort.ascending ? 'ascending' : 'descending' : 'none'} className={`px-4 py-2 text-xs font-medium text-fog-muted ${numeric.includes(i) ? 'text-right' : ''}`}><button className="focus-ring min-h-11 rounded px-1 text-left" onClick={() => { setSort({ index: i, ascending: sort?.index === i ? !sort.ascending : !numeric.includes(i) }); setPage(0); }}>{h}{sort?.index === i ? sort.ascending ? ' ↑' : ' ↓' : ''}</button></th>)}</tr></thead><tbody className="divide-y divide-surgical-steel">{sorted.slice(current * 10, current * 10 + 10).map(row => <tr key={row.id} className="transition hover:bg-surface-container-low">{row.cells.map((cell, i) => <td key={i} className={`px-4 py-4 align-top ${numeric.includes(i) ? 'text-right font-mono tabular-nums' : ''} ${i === 0 ? 'font-medium text-text-strong' : 'text-on-surface-variant'}`}>{i === 0 && row.detail ? <details><summary className="focus-ring cursor-pointer rounded leading-6">{cell}</summary><div className="mt-3 max-w-sm text-xs font-normal leading-6 text-fog-muted">{row.detail}</div></details> : typeof cell === 'number' ? number(cell) : cell ?? '—'}</td>)}</tr>)}</tbody></table></div> : <div className="grid min-h-52 place-items-center px-6 text-center"><div><Search className="mx-auto text-fog-muted" size={24} /><p className="mt-3 font-semibold text-text-strong">No matching records</p><p className="mt-2 text-sm text-fog-muted">Try another period or clear your filters.</p></div></div>}
    <div className="flex items-center justify-between border-t border-surgical-steel px-4 py-3"><span className="text-xs text-fog-muted">Page {current + 1} of {pages}</span><div className="flex gap-2"><button className={button} aria-label={`Previous ${title} page`} disabled={current === 0} onClick={() => setPage(current - 1)}><ChevronLeft size={16} /></button><button className={button} aria-label={`Next ${title} page`} disabled={current + 1 >= pages} onClick={() => setPage(current + 1)}><ChevronRight size={16} /></button></div></div>
  </div>;
}

function Trend({ report }: { report: AnalyticsReport }) {
  const [metric, setMetric] = useState<'turnover' | 'newMembers' | 'completions' | 'enrollments'>('turnover');
  const id = useId().replaceAll(':', '');
  return <Section title="The community, week by week" description="Completed weeks. The same member filters apply to every point." action={<select className={`${input} !w-auto`} aria-label="Trend metric" value={metric} onChange={e => setMetric(e.target.value as typeof metric)}><option value="turnover">Turnover · USD</option><option value="newMembers">New members</option><option value="completions">Course completions</option><option value="enrollments">Event enrolments</option></select>}>
    <div className="h-64 w-full" role="img" aria-label={`Weekly ${metric} trend. Exact values are in the table below.`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={report.trends} margin={{ top: 12, right: 12, bottom: 0, left: 0 }}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--color-chart-1)" stopOpacity={0.22} /><stop offset="100%" stopColor="var(--color-chart-1)" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--color-border-hairline)" strokeDasharray="3 6" /><XAxis dataKey="date" tickFormatter={v => String(v).slice(5)} stroke="var(--color-text-muted)" fontSize={11} tickLine={false} axisLine={false} minTickGap={24} /><YAxis stroke="var(--color-text-muted)" fontSize={11} tickLine={false} axisLine={false} width={60} tickFormatter={v => new Intl.NumberFormat('en', { notation: 'compact' }).format(v)} /><Tooltip contentStyle={{ background: 'var(--color-surface-panel)', border: '1px solid var(--color-border-hairline)', borderRadius: 12, color: 'var(--color-text-default)' }} labelFormatter={v => `Week of ${date(String(v))}`} formatter={v => [metric === 'turnover' ? money(Number(v)) : number(Number(v)), metric === 'turnover' ? 'Turnover' : metric === 'newMembers' ? 'New members' : metric === 'completions' ? 'Completions' : 'Enrolments']} /><Area type="monotone" dataKey={metric} stroke="var(--color-chart-1)" strokeWidth={2} fill={`url(#${id})`} isAnimationActive={false} /></AreaChart></ResponsiveContainer></div>
    <details className="mt-4 text-xs text-fog-muted"><summary className="focus-ring min-h-11 cursor-pointer rounded py-3">View exact weekly figures</summary><ReportTable title="Weekly figures" headers={['Week starting (UTC)', 'Turnover (USD)', 'New members', 'Completions', 'Enrolments']} numeric={[1, 2, 3, 4]} rows={report.trends.map(t => ({ id: t.date, cells: [t.date, t.turnover, t.newMembers, t.completions, t.enrollments] }))} filename={`analytics-weekly-${report.filters.start}-${report.filters.end}`} /></details>
  </Section>;
}

export function CreatorAnalyticsView({ memberName, initialFilters, initialTab }: { memberName: string; initialFilters: AnalyticsFilters; initialTab: string }) {
  const [tab, setTab] = useState<Tab>(tabs.includes(initialTab as Tab) ? initialTab as Tab : 'overview');
  const [draft, setDraft] = useState(initialFilters), [applied, setApplied] = useState(initialFilters);
  const [report, setReport] = useState<AnalyticsReport | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [validation, setValidation] = useState('');
  const [refresh, setRefresh] = useState(0), [expanded, setExpanded] = useState(false);
  useEffect(() => {
    const controller = new AbortController();
    fetch(`/api/creator/analytics?${new URLSearchParams(applied)}`, { signal: controller.signal, cache: 'no-store' }).then(async response => {
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || 'Unable to load analytics.');
      if (!controller.signal.aborted) setReport(data);
    }).catch(err => { if (!controller.signal.aborted) setError(err instanceof Error ? err.message : 'Unable to load analytics.'); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [applied, refresh]);
  useEffect(() => { const url = new URL(window.location.href); url.search = new URLSearchParams({ ...applied, tab }).toString(); window.history.replaceState(null, '', url); }, [applied, tab]);
  const apply = (filters: AnalyticsFilters) => {
    try { const parsed = parseFilters(new URLSearchParams(filters)); setDraft(parsed); setApplied(parsed); setLoading(true); setError(''); setValidation(''); } catch (err) { setValidation(err instanceof Error ? err.message : 'Invalid filters'); }
  };
  const retry = () => { setLoading(true); setError(''); setRefresh(n => n + 1); };
  const changed = JSON.stringify(draft) !== JSON.stringify(applied);
  return <AppShell active="Analytics" title="Community analytics" memberName={memberName} platformRole="influencer" routeBase="/creator">
    <div className="mx-auto w-full max-w-7xl px-4 py-7 md:px-8 md:py-10">
      <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-medium text-primary-container">Community intelligence</p><h1 className="mt-2 font-headline text-3xl font-semibold tracking-[-0.025em] text-text-strong sm:text-4xl">See what moves your community.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-on-surface-variant">Follow your traders, understand your learners, and find the events people enrol in.</p></div><Link href="/creator/revenue" className={button}>Revenue <ArrowRight size={16} /></Link></header>
      <form onSubmit={e => { e.preventDefault(); apply(draft); }} className="mt-8 rounded-xl border border-surgical-steel bg-surface-container-low p-4 sm:p-5">
        <div className="flex flex-wrap items-end gap-3"><div className="min-w-44 flex-1"><Field label="Reporting period"><select className={input} aria-label="Period preset" value="" onChange={e => { if (e.target.value) setDraft({ ...draft, ...(({ start, end }) => ({ start, end }))(defaultFilters(new Date(), Number(e.target.value))) }); }}><option value="">Choose completed weeks</option><option value="4">Last 4 completed weeks</option><option value="12">Last 12 completed weeks</option><option value="26">Last 26 completed weeks</option><option value="52">Last 52 completed weeks</option></select></Field></div><Field label="From · Monday"><input className={input} type="date" value={draft.start} onChange={e => setDraft({ ...draft, start: e.target.value })} required /></Field><Field label="To · Sunday"><input className={input} type="date" value={draft.end} onChange={e => setDraft({ ...draft, end: e.target.value })} required /></Field><button type="button" className={button} aria-expanded={expanded} aria-controls="analytics-member-filters" onClick={() => setExpanded(!expanded)}><SlidersHorizontal size={16} />Member filters{[draft.tier, draft.status, draft.source, draft.q].filter(Boolean).length ? ` (${[draft.tier, draft.status, draft.source, draft.q].filter(Boolean).length})` : ''}</button><button type="submit" disabled={loading} className="focus-ring inline-flex min-h-11 items-center gap-2 rounded-lg bg-primary-container px-5 text-sm font-semibold text-on-primary-fixed disabled:opacity-50"><Check size={16} />Apply</button></div>
        {expanded && <div id="analytics-member-filters" className="mt-5 grid gap-4 border-t border-surgical-steel pt-5 sm:grid-cols-2 xl:grid-cols-4"><Field label="Member name or exact ID"><input className={input} type="search" maxLength={100} value={draft.q} placeholder="Search members" onChange={e => setDraft({ ...draft, q: e.target.value })} /></Field><Field label="Current tier"><select className={input} value={draft.tier} onChange={e => setDraft({ ...draft, tier: e.target.value })}><option value="">All tiers</option>{[1, 2, 3, 4, 5].map(t => <option key={t} value={t}>{t === 5 ? 'Master' : `Tier ${t}`}</option>)}</select></Field><Field label="Current membership status"><select className={input} value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value })}><option value="">All statuses</option>{['active', 'expired', 'pending', 'suspended', 'cancelled', 'refunded'].map(s => <option key={s} value={s}>{s[0].toUpperCase() + s.slice(1)}</option>)}</select></Field><Field label="Access source"><select className={input} value={draft.source} onChange={e => setDraft({ ...draft, source: e.target.value })}><option value="">Paid and gifted</option><option value="stripe">Paid</option><option value="gifted">Gifted</option></select></Field></div>}
        <div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs leading-5 text-fog-muted"><p>UTC · Monday–Sunday · {changed ? 'Unapplied changes' : 'Compared with the preceding equal-length period'}</p><button type="button" className="focus-ring min-h-11 rounded px-2 text-on-surface-variant underline underline-offset-4" onClick={() => apply(defaultFilters())}>Reset filters</button></div>
        {validation && <p role="alert" className="mt-2 text-sm text-error">{validation}</p>}
      </form>
      <nav aria-label="Analytics sections" className="mt-7 flex gap-5 overflow-x-auto border-b border-surgical-steel">{tabs.map(t => <button key={t} aria-current={tab === t ? 'page' : undefined} onClick={() => setTab(t)} className={`focus-ring min-h-12 shrink-0 border-b-2 px-1 pb-3 pt-2 text-sm font-semibold capitalize transition ${tab === t ? 'border-primary-container text-primary-container' : 'border-transparent text-fog-muted hover:text-text-strong'}`}>{t}</button>)}</nav>
      {loading ? <div role="status" aria-label="Loading analytics" className="py-10"><div className="flex items-center gap-3 text-sm text-fog-muted"><RefreshCw size={17} className="motion-safe:animate-spin" />Loading your report…</div><div className="mt-6 grid grid-cols-2 gap-5 lg:grid-cols-4">{[0, 1, 2, 3].map(i => <div key={i} className="h-28 rounded-xl bg-surface-container-low motion-safe:animate-pulse" />)}</div><div className="mt-8 h-64 rounded-xl bg-surface-container-low motion-safe:animate-pulse" /></div> : error ? <div role="alert" className="my-8 rounded-xl border border-surgical-steel p-8"><h2 className="text-lg font-semibold text-text-strong">This report couldn’t load</h2><p className="mt-2 text-sm text-on-surface-variant">{error}</p><button className={`${button} mt-5`} onClick={retry}><RefreshCw size={16} />Try again</button></div> : report && <div className="py-7">
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3 text-xs text-fog-muted"><p>{date(report.filters.start)} – {date(report.filters.end)} <span className="mx-2">/</span> Comparing {date(report.previous.start)} – {date(report.previous.end)}{applied.q && ` · Member: ${applied.q}`}{applied.tier && ` · Tier ${applied.tier}`}{applied.status && ` · ${applied.status}`}{applied.source && ` · ${applied.source === 'stripe' ? 'Paid' : 'Gifted'}`}</p><button className="focus-ring flex min-h-11 items-center gap-2 rounded px-2" onClick={retry}><RefreshCw size={13} />Updated {new Date(report.generatedAt).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', timeZone: 'UTC' })} UTC</button></div>
        {tab === 'overview' && <Overview report={report} navigate={setTab} />}
        <div hidden={tab !== 'trading'}><Trading key={JSON.stringify(applied)} report={report} /></div>
        <div hidden={tab !== 'courses'}><Courses key={JSON.stringify(applied)} report={report} /></div>
        <div hidden={tab !== 'events'}><Events key={JSON.stringify(applied)} report={report} /></div>
        {tab === 'referrals' && <Referrals />}
      </div>}
    </div>
  </AppShell>;
}

function Overview({ report: r, navigate }: { report: AnalyticsReport; navigate: (tab: Tab) => void }) {
  const m = r.metrics;
  return <div className="space-y-9"><div className="grid grid-cols-2 gap-x-4 border-y border-surgical-steel sm:divide-x sm:divide-surgical-steel lg:grid-cols-4"><Metric label="Recorded turnover" value={money(m.turnover)} detail={delta(m.turnover, m.previousTurnover)} /><Metric label="New members" value={number(m.newMembers)} detail={delta(m.newMembers, m.previousNewMembers)} /><Metric label="First course completions" value={number(m.completions)} detail={delta(m.completions, m.previousCompletions)} /><Metric label="Event enrolments" value={number(m.eventEnrollments)} detail={delta(m.eventEnrollments, m.previousEventEnrollments)} /></div>
    <div className="grid gap-9 xl:grid-cols-[minmax(0,2fr)_minmax(240px,1fr)]"><Trend report={r} /><Section title="Where members are now" description={`${number(m.members)} matching members · ${number(m.activeMemberships)} active memberships`}><div className="space-y-5">{r.tiers.map(t => <div key={t.tier}><div className="mb-2 flex justify-between text-sm"><span className="text-on-surface-variant">{t.tier === 5 ? 'Master' : `Tier ${t.tier}`}</span><span className="font-mono text-text-strong">{number(t.count)}</span></div><div className="h-2 overflow-hidden rounded-sm bg-surgical-steel"><div className="h-full rounded-sm bg-primary-container" style={{ width: `${m.members ? t.count / m.members * 100 : 0}%` }} /></div></div>)}</div><p className="mt-6 text-xs leading-5 text-fog-muted">Current membership and tier snapshots. They do not represent historical activity or retention.</p></Section></div>
    <Section title="Explore the leaders" description="Different measures of contribution. Open a report to compare everyone."><div className="divide-y divide-surgical-steel border-y border-surgical-steel">{[
      { tab: 'trading' as const, icon: BarChart3, title: 'Highest turnover', name: r.trading.find(t => t.recordedWeeks)?.name ?? 'No recorded turnover', detail: r.trading.find(t => t.recordedWeeks) ? money(r.trading.find(t => t.recordedWeeks)!.amount) : 'Selected weeks' },
      { tab: 'courses' as const, icon: BookOpen, title: 'Most watched course', name: r.courses.find(c => c.viewers)?.title ?? 'No course viewing yet', detail: `${number(r.courses[0]?.viewers ?? 0)} unique viewers · lifetime` },
      { tab: 'events' as const, icon: CalendarDays, title: 'Most enrolled event', name: r.events.find(e => e.enrollments)?.title ?? 'No enrolments this period', detail: `${number(r.events[0]?.enrollments ?? 0)} enrolments · selected period` },
    ].map(item => <button key={item.tab} onClick={() => navigate(item.tab)} className="focus-ring flex min-h-24 w-full items-center gap-4 py-4 text-left transition hover:bg-surface-container-low sm:px-4"><item.icon size={20} className="shrink-0 text-primary-container" /><div className="min-w-0 flex-1"><p className="text-xs text-fog-muted">{item.title}</p><p className="mt-1 truncate text-sm font-semibold text-text-strong">{item.name}</p><p className="mt-1 text-xs text-fog-muted sm:hidden">{item.detail}</p></div><p className="hidden text-xs text-on-surface-variant sm:block">{item.detail}</p><ArrowRight size={17} className="shrink-0 text-fog-muted" /></button>)}</div></Section>
    <Note>Retention, active learning days, and historical watch-time trends need dated activity tracking. Current progress is available in Courses; unavailable metrics are never counted as zero.</Note>
  </div>;
}

function Trading({ report: r }: { report: AnalyticsReport }) {
  const [entry, setEntry] = useState('all'), [minimum, setMinimum] = useState('');
  const rows = r.trading.filter(t => (entry === 'all' || (entry === 'recorded' ? t.recordedWeeks > 0 : t.recordedWeeks === 0)) && (!minimum || t.amount >= Number(minimum)));
  return <div className="space-y-8"><div className="grid grid-cols-2 gap-4 border-b border-surgical-steel lg:grid-cols-4"><Metric label="Selected-period turnover" value={money(r.metrics.turnover)} detail={delta(r.metrics.turnover, r.metrics.previousTurnover)} /><Metric label="Contributing members" value={number(r.metrics.contributors)} detail="Members with positive turnover" /><Metric label="Median contribution" value={money(r.metrics.median)} detail="Among positive contributors" /><Metric label="No entries in period" value={number(r.metrics.missingMembers)} detail="Missing records, not recorded zero" /></div><Section title="Turnover leaderboard" description="Highest selected-period turnover first. Lifetime totals include every saved week." action={<Link href="/creator/members/turnover" className={button}>Open turnover workspace <ArrowRight size={15} /></Link>}><div className="mb-5 flex flex-wrap gap-4"><Field label="Entry coverage"><select className={`${input} !w-auto`} value={entry} onChange={e => setEntry(e.target.value)}><option value="all">All members</option><option value="recorded">Has recorded entries</option><option value="missing">No entries in period</option></select></Field><Field label="Minimum period turnover · USD"><input className={input} type="number" min="0" step="0.01" value={minimum} placeholder="No minimum" onChange={e => setMinimum(e.target.value)} /></Field></div><ReportTable title="Turnover leaderboard" filename={`analytics-trading-${r.filters.start}-${r.filters.end}`} headers={['Member', 'Tier', 'Period (USD)', 'Previous (USD)', 'Lifetime (USD)', 'Share (%)', 'Weeks recorded']} numeric={[1, 2, 3, 4, 5, 6]} rows={rows.map(t => ({ id: t.id, cells: [t.name, t.tier, t.recordedWeeks ? t.amount : null, t.previous, t.lifetime, t.recordedWeeks ? t.share : null, t.recordedWeeks], detail: <><p className="break-all">Member ID: {t.id}</p><p className="capitalize">Membership: {t.status}</p><p>Last saved: {date(t.updated)}</p><p>{delta(t.amount, t.previous)}</p></> }))} /></Section><Note>These are manually recorded turnover amounts. Platform breakdowns and withdrawable balances will appear once platform-linked credit records are available. A saved turnover total is not proof of a completed payout.</Note></div>;
}

function Courses({ report: r }: { report: AnalyticsReport }) {
  const [course, setCourse] = useState(''), [search, setSearch] = useState(''), [status, setStatus] = useState('');
  const courses = r.courses.filter(c => (!course || c.id === course) && (!status || c.status === status));
  const learners = r.learners.filter(l => l.name.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-8"><Note><strong className="font-semibold text-text-strong">Two time scopes:</strong> unique viewers and recorded progress hours are lifetime snapshots. Enrolments and first completions use the selected dates. Progress hours are accumulated saved progress, not a verified history of playback sessions.</Note><Section title="Course performance" description="Most watched ranks by lifetime unique viewers within your member filters. Expand a course to inspect its lessons."><div className="mb-5 flex flex-wrap gap-4"><Field label="Course"><select className={`${input} !w-auto`} value={course} onChange={e => setCourse(e.target.value)}><option value="">All courses</option>{r.courses.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></Field><Field label="Course status"><select className={`${input} !w-auto`} value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></Field></div><ReportTable title="Course performance" filename={`analytics-courses-${r.filters.start}-${r.filters.end}`} headers={['Course', 'Unique viewers · lifetime', 'Progress hours · lifetime', 'Enrolments · period', 'First completions · period', 'Cohort complete (%)']} numeric={[1, 2, 3, 4, 5]} rows={courses.map(c => ({ id: c.id, cells: [c.title, c.viewers, c.hours, c.enrollments, c.completions, c.cohortRate], detail: <><p className="capitalize">{c.status}</p><p className="mb-3">{c.cohortCompleted} of {c.enrollments} members enrolled in this period are currently complete. Observed through {date(r.generatedAt)}.</p>{c.lessons.length ? <ol className="space-y-2">{c.lessons.map(l => <li key={l.id}><span className="text-on-surface">{l.title}</span><br />{l.viewers} viewers · {l.completed} completed · lifetime</li>)}</ol> : <p>No lessons yet.</p>}</> }))} /></Section><Section title="Learner leaderboard" description="First course completions, then lesson completions in the selected period. Lifetime progress hours are a separate measure."><div className="mb-5 max-w-sm"><Field label="Search learners"><input className={input} type="search" value={search} placeholder="Learner name" onChange={e => setSearch(e.target.value)} /></Field></div><ReportTable title="Learner leaderboard" filename={`analytics-learners-${r.filters.start}-${r.filters.end}`} headers={['Member', 'Tier', 'First courses · period', 'Lessons completed · period', 'Progress hours · lifetime', 'Last learning activity · UTC']} numeric={[1, 2, 3, 4]} rows={learners.map(l => ({ id: l.id, cells: [l.name, l.tier, l.courses, l.lessons, l.hours, l.lastWatched ? l.lastWatched.slice(0, 10) : null], detail: <p className="break-all">Member ID: {l.id}</p> }))} /></Section></div>;
}

function Events({ report: r }: { report: AnalyticsReport }) {
  const [host, setHost] = useState(''), [status, setStatus] = useState(''), [search, setSearch] = useState('');
  const rows = r.events.filter(e => (!host || e.host_name === host) && (!status || e.status === status) && e.title.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-8"><div className="grid gap-4 border-b border-surgical-steel sm:grid-cols-3"><Metric label="Event enrolments" value={number(r.metrics.eventEnrollments)} detail={delta(r.metrics.eventEnrollments, r.metrics.previousEventEnrollments)} /><Metric label="Unique enrollees" value={number(r.metrics.uniqueEnrollees)} detail="Distinct members enrolled this period" /><Metric label="Repeat enrollees" value={number(r.metrics.repeatEnrollees)} detail="Enrolled in two or more events this period" /></div><Section title="Events people enrol in" description="Ranked by enrolments created in the selected period, regardless of the event date."><div className="mb-5 grid gap-4 sm:grid-cols-3"><Field label="Find an event"><input className={input} type="search" placeholder="Event title" value={search} onChange={e => setSearch(e.target.value)} /></Field><Field label="Host"><select className={input} value={host} onChange={e => setHost(e.target.value)}><option value="">All hosts</option>{[...new Set(r.events.map(e => e.host_name))].sort().map(h => <option key={h}>{h}</option>)}</select></Field><Field label="Event status"><select className={input} value={status} onChange={e => setStatus(e.target.value)}><option value="">All published events</option>{['upcoming', 'live', 'completed'].map(s => <option key={s} value={s}>{s}</option>)}</select></Field></div><ReportTable title="Event enrolments" filename={`analytics-events-${r.filters.start}-${r.filters.end}`} headers={['Event', 'Host', 'Event date · UTC', 'Status', 'Enrolments · period', 'Previous period', 'Current total']} numeric={[4, 5, 6]} rows={rows.map(e => ({ id: e.id, cells: [e.title, e.host_name, e.starts_at.slice(0, 10), e.status, e.enrollments, e.previous, e.lifetime], detail: <p>Event ID: {e.id}</p> }))} /></Section><Note>Enrolments measure interest, not attendance. Cancelled and draft events are excluded. Withdrawn enrolments are removed by the existing event flow, so these figures describe retained enrolments; historical cancellations and capacity are not tracked.</Note></div>;
}

function Referrals() {
  return <section className="grid gap-9 py-5 lg:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)]"><div><Users size={30} className="text-primary-container" /><p className="mt-5 inline-flex rounded-md border border-surgical-steel px-3 py-1 text-xs text-on-surface-variant">Not tracked yet</p><h2 className="mt-4 text-2xl font-semibold tracking-tight text-text-strong">Turn recommendations into measurable growth.</h2><p className="mt-4 max-w-lg text-sm leading-7 text-on-surface-variant">Your referral report will connect signups to first membership payments, so you can see who brings paying members into the community.</p><div className="mt-6 border-y border-surgical-steel py-5 text-sm leading-7 text-fog-muted"><p className="font-semibold text-text-strong">The reward rule</p><p>A referrer earns $5 credit after the referred member’s first successful membership payment. A refund reverses that reward.</p></div></div><div className="self-center"><h3 className="text-sm font-semibold text-text-strong">What you’ll be able to compare</h3><ul className="mt-4 divide-y divide-surgical-steel text-sm text-on-surface-variant">{['Top referrers by qualifying paid members', 'Referred signups and signup-to-paid conversion', 'Rewards earned and reversed', 'Learning and event engagement of referred members'].map(t => <li key={t} className="flex gap-3 py-4"><ArrowRight size={16} className="mt-0.5 shrink-0 text-primary-container" />{t}</li>)}</ul><p className="mt-4 text-xs leading-6 text-fog-muted">Referral attribution and reward records are not connected yet. This section will show real rankings when those records are available.</p></div></section>;
}
