"use client";

import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays, CheckCircle2, Clock3, Play, Sparkles } from "lucide-react";

import { AppShell } from "@/components/layout/AppShell";
import { withRouteBase } from "@/lib/navigation/paths";
import type { DashboardData } from "./DashboardView";

const eventDate = (value: string) => new Intl.DateTimeFormat(undefined, { weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));

export function TerminalDashboard({ data, routeBase = "" }: { data: DashboardData; routeBase?: string }) {
  const courseHref = (courseId?: string) => withRouteBase(routeBase, courseId ? `/courses/${courseId}` : "/courses");
  const activeCount = data.enrolledCourses.filter((course) => !course.isCompleted).length;

  return <AppShell active="Dashboard" title="Member overview" terminalHeader isMaster={data.isMaster} memberName={data.memberName} platformRole={data.platformRole} currentTier={data.currentTier} notifications={data.notifications} routeBase={routeBase}>
    <main className="mx-auto w-full max-w-[1280px] px-4 py-8 sm:px-6 lg:px-10 lg:py-10">
      <header className="mb-8"><p className="terminal-label">Member home</p><h1 className="mt-2 font-headline text-3xl font-semibold tracking-tight text-white sm:text-4xl">Welcome back, {data.memberName}</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-on-surface-variant sm:text-base">Your complete Stoic curriculum is open. Continue a course or choose any released lesson that fits today’s practice.</p></header>

      <div className="grid gap-6 lg:grid-cols-12">
        <section className="terminal-card p-6 lg:col-span-4"><div className="flex items-start justify-between gap-5"><div><p className="terminal-label">Course library</p><h2 className="mt-2 font-headline text-2xl font-semibold text-white">{data.totalLessons} available</h2><p className="mt-2 text-sm text-fog-muted">Every published course is open to active members.</p></div><BookOpen size={24} className="text-primary-container" /></div><Link href={courseHref()} className="mt-6 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-primary-container">Browse all courses <ArrowRight size={14} /></Link></section>
        <section className="terminal-card p-6 lg:col-span-4"><p className="terminal-label">Your progress</p><h2 className="mt-2 font-headline text-2xl font-semibold text-white">{data.completedLessons} completed</h2><p className="mt-2 text-sm text-fog-muted">{activeCount ? `${activeCount} course${activeCount === 1 ? " is" : "s are"} currently in progress.` : "Start any course to begin tracking progress."}</p><div className="mt-6 h-1.5 overflow-hidden rounded-full bg-surface-container-highest"><div className="h-full rounded-full bg-primary-container" style={{ width: `${data.totalLessons ? Math.round((data.completedLessons / data.totalLessons) * 100) : 0}%` }} /></div></section>
        <section className="terminal-card border-t-2 border-t-primary-container p-6 lg:col-span-4"><p className="terminal-label text-primary-container">No learning gates</p><h2 className="mt-3 font-headline text-lg font-semibold text-white">Study in your own order</h2><p className="mt-2 text-sm leading-relaxed text-on-surface-variant">Course tiers and prerequisites no longer restrict what you can watch. Scheduled lessons appear when their release time arrives.</p></section>

        <section className="terminal-card overflow-hidden lg:col-span-8 lg:grid lg:min-h-[315px] lg:grid-cols-2"><div className="flex flex-col justify-center p-7 sm:p-8"><p className="terminal-label">Continue learning</p><h2 className="mt-3 font-headline text-2xl font-semibold leading-tight text-white">{data.activeLesson?.title ?? "Choose your next course"}</h2><p className="mt-4 text-sm leading-relaxed text-on-surface-variant">{data.activeLesson?.description ?? "Browse the full library and begin with the subject most useful to your current practice."}</p>{data.activeLesson && <p className="mt-4 text-xs font-semibold text-primary-container">{data.activeLesson.completedVideos} / {data.activeLesson.totalVideos} lessons complete · {data.activeLesson.remainingMinutes} min remaining</p>}<Link href={courseHref(data.activeLesson?.id)} className="mt-7 inline-flex w-fit items-center gap-2 rounded-full bg-primary-container px-6 py-3 text-xs font-bold uppercase tracking-wider text-on-primary-fixed"><Play size={14} fill="currentColor" />{data.activeLesson ? "Resume course" : "Browse courses"}</Link></div><CoursePreview progress={data.activeLesson?.progress ?? 0} title={data.activeLesson?.title ?? "Open curriculum"} /></section>

        <section className="terminal-card flex flex-col p-7 lg:col-span-4"><div className="flex items-center justify-between gap-3"><p className="terminal-label">Upcoming live</p><span className="text-xs text-primary-container">{data.upcomingEvent?.status ?? "Calendar"}</span></div>{data.upcomingEvent ? <><div className="mt-7 flex-1"><h2 className="font-headline text-xl font-semibold text-white">{data.upcomingEvent.title}</h2><p className="mt-3 text-sm leading-relaxed text-on-surface-variant">{data.upcomingEvent.description || "A live session for Stoicverse members."}</p><p className="mt-5 flex items-center gap-2 text-xs text-primary-container"><Clock3 size={14} />{eventDate(data.upcomingEvent.starts_at)}</p></div><Link href={withRouteBase(routeBase, "/events")} className="mt-7 inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-surgical-steel text-xs font-semibold uppercase tracking-wider text-on-surface hover:border-primary-container"><CalendarDays size={15} />View event</Link></> : <><div className="mt-7 flex-1"><h2 className="font-headline text-xl font-semibold text-white">No session scheduled</h2><p className="mt-3 text-sm leading-relaxed text-on-surface-variant">Visit the events directory as new live sessions are published.</p></div><Link href={withRouteBase(routeBase, "/events")} className="mt-7 inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-surgical-steel text-xs font-semibold uppercase tracking-wider text-on-surface">Browse calendar <ArrowRight size={14} /></Link></>}</section>

        <section className="terminal-card overflow-hidden lg:col-span-7"><div className="flex flex-wrap items-end justify-between gap-4 px-6 py-5"><div><h2 className="font-headline text-xl font-semibold text-white">Your courses</h2><p className="mt-1 text-sm text-fog-muted">Enrolled courses and saved progress.</p></div><Link href={courseHref()} className="inline-flex min-h-11 items-center rounded-full border border-surgical-steel px-4 text-xs font-semibold uppercase tracking-wider text-on-surface hover:border-primary-container">All courses <ArrowRight size={14} className="ml-2" /></Link></div><div className="divide-y divide-surgical-steel border-t border-surgical-steel">{data.enrolledCourses.slice(0, 3).map((course) => <RecordedCourse key={course.id} course={course} href={courseHref(course.id)} />)}{!data.enrolledCourses.length && <p className="px-6 py-10 text-center text-sm text-on-surface-variant">Enroll from the course library to keep a course on your dashboard.</p>}</div></section>
        <section className="terminal-card relative flex min-h-[260px] flex-col items-center justify-center overflow-hidden p-7 text-center lg:col-span-5"><div className="absolute inset-0 bg-primary-container/[0.04]" /><div className="relative grid size-16 place-items-center rounded-full border border-primary-container/30 bg-primary-container/10 text-primary-container"><Sparkles size={28} /></div><h2 className="relative mt-6 font-headline text-xl font-semibold text-white">Elite mentorship</h2><p className="relative mt-3 max-w-sm text-sm leading-relaxed text-on-surface-variant">Accelerate your practice with personalised guidance and direct access to a Stoic mentor.</p><Link href={withRouteBase(routeBase, "/mentorship")} className="relative mt-6 rounded-full bg-white px-6 py-3 text-xs font-bold uppercase tracking-wider text-surface hover:bg-primary-container">Explore mentorship</Link></section>
      </div>
    </main>
  </AppShell>;
}

function CoursePreview({ progress, title }: { progress: number; title: string }) { return <div className="relative min-h-[220px] overflow-hidden border-t border-surgical-steel bg-surface-container-highest lg:min-h-0 lg:border-l lg:border-t-0"><div className="absolute inset-0 bg-primary-container/[0.06]" /><div className="relative flex h-full min-h-[220px] flex-col justify-end p-7"><p className="terminal-label">Active course</p><p className="mt-2 text-sm font-semibold uppercase tracking-wider text-white line-clamp-2">{title}</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-surface-container-lowest"><div className="h-full bg-primary-container" style={{ width: `${progress}%` }} /></div><p className="mt-2 text-xs text-primary-container">{progress}% complete</p></div></div>; }

function RecordedCourse({ course, href }: { course: DashboardData["enrolledCourses"][number]; href: string }) { return <Link href={href} className="group grid gap-3 px-6 py-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center hover:bg-surface-container-high/40"><div><h3 className="font-semibold text-white group-hover:text-primary-container">{course.title}</h3><p className="mt-1 text-xs text-fog-muted">{course.isCompleted ? "Completed · ready to revisit" : `${course.completedVideos} of ${course.totalVideos} lessons complete · ${course.remainingMinutes} min remaining`}</p><div className="mt-3 h-1.5 max-w-lg overflow-hidden rounded-full bg-surface-container-highest"><div className="h-full rounded-full bg-primary-container" style={{ width: `${course.progress}%` }} /></div></div><span className="inline-flex items-center gap-2 text-xs font-semibold text-primary-container">{course.isCompleted && <CheckCircle2 size={15} />}{course.isCompleted ? "Review" : `${course.progress}%`}<ArrowRight size={14} /></span></Link>; }
