"use client";

import Link from "next/link";
import { ArrowRight, CalendarDays, CheckCircle2, Clock3, Lock, Play, Sparkles } from "lucide-react";
import { useMemo } from "react";

import { AppShell } from "@/components/layout/AppShell";
import { withRouteBase } from "@/lib/navigation/paths";
import type { DashboardData } from "./DashboardView";

const eventDate = (value: string) => new Intl.DateTimeFormat(undefined, { weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));

export function TerminalDashboard({ data, routeBase = "" }: { data: DashboardData; routeBase?: string }) {
  const tierProgress = data.currentTierTotal ? Math.round((data.currentTierCompleted / data.currentTierTotal) * 100) : 0;
  const remainingCourses = useMemo(() => data.tierProgressDetails.reduce((total, tier) => total + Math.max(0, tier.totalCount - tier.completedCount), 0), [data.tierProgressDetails]);
  const courseHref = (courseId?: string) => withRouteBase(routeBase, courseId ? `/courses/${courseId}` : "/courses");

  return <AppShell active="Dashboard" title="Terminal overview" terminalHeader isMaster={data.isMaster} memberName={data.memberName} platformRole={data.platformRole} currentTier={data.currentTier} notifications={data.notifications} routeBase={routeBase}>
    <main className="mx-auto w-full max-w-[1280px] px-4 py-8 sm:px-6 lg:px-10 lg:py-10">
      <header className="mb-8"><p className="font-label text-xs uppercase tracking-[0.16em] text-primary-container">Member terminal</p><h1 className="mt-2 font-headline text-3xl font-semibold tracking-tight text-white sm:text-4xl">Terminal overview</h1><p className="mt-2 text-sm text-on-surface-variant sm:text-base">Welcome back, {data.memberName}. Continue your disciplined progression through the Stoic curriculum.</p></header>
      <div className="grid gap-6 lg:grid-cols-12">
        <section className="terminal-card p-6 lg:col-span-4"><div className="flex items-start justify-between gap-5"><div className="min-w-0"><p className="terminal-label">Current tier</p><h2 className="mt-2 font-headline text-2xl font-semibold text-white [text-wrap:balance]">{data.isMaster ? "Master Zone" : data.currentTierTitle}</h2><p className="mt-2 text-sm text-fog-muted">{data.isMaster ? "The Stoic pathway is complete." : `Tier ${data.currentTier} of ${data.tierProgressDetails.length} is active.`}</p></div><TierProgressCircle value={data.isMaster ? 100 : tierProgress} /></div><div className="mt-7 border-t border-surgical-steel pt-4"><div className="flex items-center justify-between gap-4 text-sm"><span className="text-on-surface-variant">{data.isMaster ? "All pathway milestones completed" : `${data.currentTierCompleted} of ${data.currentTierTotal} courses complete`}</span><span className="font-label text-xs text-primary-container">{data.isMaster ? "MASTERED" : "IN PROGRESS"}</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-surface-container-highest"><div className="h-full rounded-full bg-primary-container transition-[width] duration-200 motion-reduce:transition-none" style={{ width: `${data.isMaster ? 100 : tierProgress}%` }} /></div></div></section>
        <section className="terminal-card p-6 lg:col-span-4"><div className="flex items-start justify-between gap-4"><div><p className="terminal-label">Curriculum</p><h2 className="mt-2 font-headline text-xl font-semibold text-white">Your learning path</h2></div><span className="font-label text-xs text-fog-muted">{data.completedLessons} / {data.totalLessons}</span></div><div className="mt-5 space-y-3">{data.tierProgressDetails.map((tier) => { const complete = tier.status === "completed" ? 100 : tier.status === "active" && tier.totalCount ? Math.round((tier.completedCount / tier.totalCount) * 100) : 0; return <div key={tier.level} className="grid grid-cols-[minmax(4.5rem,0.9fr)_minmax(0,1fr)_2.5rem] items-center gap-3"><span className={`truncate text-xs font-medium ${tier.status === "locked" ? "text-fog-muted" : "text-on-surface"}`}>{tier.title}</span><div className="h-1 overflow-hidden rounded-full bg-surface-container-highest"><div className={`h-full rounded-full ${tier.status === "locked" ? "bg-surgical-steel" : "bg-primary-container"}`} style={{ width: `${complete}%` }} /></div><span className="text-right font-label text-[10px] text-fog-muted">{tier.completedCount}/{tier.totalCount}</span></div>; })}</div></section>
        <section className="terminal-card border-t-2 border-t-primary-container p-6 lg:col-span-4"><p className="terminal-label text-primary-container">Pathway status</p><h2 className="mt-3 font-headline text-lg font-semibold text-white">{data.isMaster ? "Highest attainment reached" : "Your next milestone"}</h2><p className="mt-2 text-sm leading-relaxed text-on-surface-variant">{data.isMaster ? "You have completed the complete Stoic pathway." : `${remainingCourses} course${remainingCourses === 1 ? "" : "s"} remain before Master Zone unlocks.`}</p><Link href={courseHref()} className="mt-5 inline-flex items-center gap-2 font-label text-xs font-semibold uppercase tracking-wider text-primary-container transition hover:gap-3">Explore curriculum <ArrowRight size={14} /></Link></section>
        <section className="terminal-card overflow-hidden lg:col-span-8 lg:grid lg:min-h-[315px] lg:grid-cols-2"><div className="flex flex-col justify-center p-7 sm:p-8"><p className="terminal-label">Continue learning</p><h2 className="mt-3 font-headline text-2xl font-semibold leading-tight text-white">{data.activeLesson?.title ?? "Choose your next course"}</h2><p className="mt-4 text-sm leading-relaxed text-on-surface-variant">{data.activeLesson?.description ?? "Your full curriculum is ready whenever you are. Select a course to begin building your practice."}</p>{data.activeLesson && <p className="mt-4 font-label text-xs uppercase tracking-wider text-primary-container">{data.activeLesson.completedVideos} / {data.activeLesson.totalVideos} lessons complete · {data.activeLesson.remainingMinutes} min remaining</p>}<Link href={courseHref(data.activeLesson?.id)} className="mt-7 inline-flex w-fit items-center gap-2 rounded bg-primary-container px-6 py-3 font-label text-xs font-bold uppercase tracking-wider text-on-primary-fixed transition hover:brightness-110"><Play size={14} fill="currentColor" />{data.activeLesson ? "Resume session" : "Browse courses"}</Link></div><TerminalPreview progress={data.activeLesson?.progress ?? 0} title={data.activeLesson?.title ?? "Stoic curriculum"} /></section>
        <section className="terminal-card flex flex-col p-7 lg:col-span-4"><div className="flex items-center justify-between gap-3"><p className="terminal-label">Upcoming live</p><span className="font-label text-[10px] uppercase tracking-wider text-primary-container">{data.upcomingEvent?.status ?? "Calendar"}</span></div>{data.upcomingEvent ? <><div className="mt-7 flex-1"><h2 className="font-headline text-xl font-semibold text-white">{data.upcomingEvent.title}</h2><p className="mt-3 text-sm leading-relaxed text-on-surface-variant">{data.upcomingEvent.description || "A live session for Stoicverse members."}</p><p className="mt-5 flex items-center gap-2 font-label text-xs text-primary-container"><Clock3 size={14} />{eventDate(data.upcomingEvent.starts_at)}</p></div><Link href={withRouteBase(routeBase, "/events")} className="mt-7 inline-flex min-h-12 items-center justify-center gap-2 rounded border border-surgical-steel font-label text-xs font-semibold uppercase tracking-wider text-on-surface transition hover:border-primary-container hover:bg-primary-container/10"><CalendarDays size={15} />View event</Link></> : <><div className="mt-7 flex-1"><h2 className="font-headline text-xl font-semibold text-white">No session scheduled</h2><p className="mt-3 text-sm leading-relaxed text-on-surface-variant">Visit the events directory to see new live sessions as they are published.</p></div><Link href={withRouteBase(routeBase, "/events")} className="mt-7 inline-flex min-h-12 items-center justify-center gap-2 rounded border border-surgical-steel font-label text-xs font-semibold uppercase tracking-wider text-on-surface transition hover:border-primary-container hover:bg-primary-container/10">Browse calendar <ArrowRight size={14} /></Link></>}</section>
        <section className="terminal-card overflow-hidden lg:col-span-7"><div className="flex flex-wrap items-end justify-between gap-4 px-6 py-5"><div><h2 className="font-headline text-xl font-semibold text-white [text-wrap:balance]">Recorded sessions</h2><p className="mt-1 text-sm text-fog-muted">{data.enrolledCourses.length ? `${data.enrolledCourses.length} enrolled course${data.enrolledCourses.length === 1 ? "" : "s"} · ${data.enrolledCourses.reduce((minutes, course) => minutes + course.remainingMinutes, 0)} min left to study` : "Your active course sessions will appear here."}</p></div><Link href={courseHref()} className="inline-flex min-h-11 items-center rounded-full border border-surgical-steel px-4 font-label text-xs font-semibold uppercase tracking-wider text-on-surface transition-colors hover:border-primary-container hover:text-primary-container">All courses <ArrowRight size={14} className="ml-2" /></Link></div><div className="divide-y divide-surgical-steel border-t border-surgical-steel">{data.enrolledCourses.slice(0, 3).map((course) => <RecordedSessionRow key={course.id} course={course} href={courseHref(course.id)} />)}{!data.enrolledCourses.length && <p className="px-6 py-10 text-center text-sm text-on-surface-variant">Enroll in a course to start tracking your progress here.</p>}</div></section>
        <section className="terminal-card relative flex min-h-[260px] flex-col items-center justify-center overflow-hidden p-7 text-center lg:col-span-5"><div className="absolute inset-0 bg-primary-container/[0.04]" /><div className="relative grid size-16 place-items-center rounded-full border border-primary-container/30 bg-primary-container/10 text-primary-container"><Sparkles size={28} /></div><h2 className="relative mt-6 font-headline text-xl font-semibold text-white">Elite mentorship</h2><p className="relative mt-3 max-w-sm text-sm leading-relaxed text-on-surface-variant">Accelerate your progress with personalised guidance, reviews, and direct access to a Stoic mentor.</p><Link href={withRouteBase(routeBase, "/mentorship")} className="relative mt-6 rounded bg-white px-6 py-3 font-label text-xs font-bold uppercase tracking-wider text-surface transition hover:bg-primary-container">Explore mentorship</Link></section>
      </div>
    </main>
  </AppShell>;
}

function TerminalPreview({ progress, title }: { progress: number; title: string }) { return <div className="relative min-h-[220px] overflow-hidden border-t border-surgical-steel bg-surface-container-highest lg:min-h-0 lg:border-l lg:border-t-0"><div className="absolute inset-0 opacity-25 [background-image:linear-gradient(#4edea3_1px,transparent_1px),linear-gradient(90deg,#4edea3_1px,transparent_1px)] [background-size:32px_32px]" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(78,222,163,0.22),transparent_42%),linear-gradient(135deg,rgba(5,20,36,0.2),rgba(1,15,31,0.9))]" /><div className="relative flex h-full min-h-[220px] flex-col justify-end p-7"><p className="terminal-label">Active module</p><p className="mt-2 font-label text-sm uppercase tracking-wider text-white line-clamp-2">{title}</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-surface-container-lowest"><div className="h-full bg-primary-container" style={{ width: `${progress}%` }} /></div><p className="mt-2 font-label text-xs text-primary-container">{progress}% complete</p></div></div>; }

function TierProgressCircle({ value }: { value: number }) {
  const radius = 31;
  const circumference = 2 * Math.PI * radius;
  const percentage = Math.min(Math.max(value, 0), 100);
  const dashOffset = circumference - (percentage / 100) * circumference;

  return <div className="relative grid size-20 shrink-0 place-items-center" aria-label={`${percentage}% current tier progress`}><svg className="size-20 -rotate-90" aria-hidden="true"><circle cx="40" cy="40" r={radius} fill="transparent" stroke="currentColor" strokeWidth="5" className="text-surface-container-highest" /><circle cx="40" cy="40" r={radius} fill="transparent" stroke="currentColor" strokeWidth="5" strokeLinecap="round" strokeDasharray={circumference} strokeDashoffset={dashOffset} className="text-primary-container transition-[stroke-dashoffset] duration-300 motion-reduce:transition-none" /></svg><span className="absolute text-center"><span className="block font-label text-sm font-semibold text-white">{percentage}%</span><span className="block font-label text-[8px] uppercase tracking-wide text-fog-muted">complete</span></span></div>;
}

function RecordedSessionRow({ course, href }: { course: DashboardData["enrolledCourses"][number]; href: string }) {
  const progressLabel = course.isCompleted ? "Completed" : `${course.progress}% complete`;
  const detail = course.isCompleted ? "Ready to revisit" : `${course.completedVideos} of ${course.totalVideos} lessons watched`;

  return (
    <Link href={href} className="group grid gap-4 px-6 py-5 transition-colors hover:bg-surface-container-high/45 sm:grid-cols-[10rem_minmax(0,1fr)] lg:grid-cols-[10rem_minmax(0,1fr)_7rem] lg:items-center">
      <div className="relative aspect-video overflow-hidden rounded-md border border-surgical-steel bg-surface-container-lowest">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_68%_22%,rgba(78,222,163,0.2),transparent_42%)]" />
        {course.thumbnailVideoId && <video aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-85" src={`/api/courses/videos/${course.thumbnailVideoId}/stream`} muted playsInline preload="metadata" />}
        <div className="absolute inset-0 bg-surface/15" />
        <span className="absolute inset-0 m-auto grid size-9 place-items-center rounded-full border border-primary-container/40 bg-surface/90 text-primary-container">
          {course.isCompleted ? <CheckCircle2 size={16} /> : <Play size={14} fill="currentColor" />}
        </span>
        <span className="absolute bottom-2 left-2 rounded bg-surface/90 px-2 py-1 font-label text-[9px] uppercase tracking-wider text-white">{course.totalVideos} lessons</span>
      </div>
      <div className="min-w-0">
        <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
          <h3 className="font-headline text-base font-semibold text-white [text-wrap:balance] group-hover:text-primary-container">{course.title}</h3>
          <span className="font-label text-xs font-semibold text-primary-container">{progressLabel}</span>
        </div>
        <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-fog-muted">
          <span>{detail}</span>
          {!course.isCompleted && <span className="inline-flex items-center gap-1.5"><Clock3 size={13} />{course.remainingMinutes} min remaining</span>}
        </div>
        <div className="mt-4 h-1.5 overflow-hidden rounded-full bg-surface-container-highest"><div className="h-full rounded-full bg-primary-container transition-[width] duration-200 motion-reduce:transition-none" style={{ width: `${course.progress}%` }} /></div>
      </div>
      <span className="hidden justify-self-end lg:inline-flex items-center gap-1 font-label text-xs uppercase tracking-wider text-fog-muted transition-colors group-hover:text-primary-container">Open <ArrowRight size={14} /></span>
    </Link>
  );
}
function CourseProgress({ course, href }: { course: DashboardData["enrolledCourses"][number]; href: string }) { return <Link href={href} className="group -mx-2 flex items-center gap-4 rounded-lg p-2 transition hover:bg-surface-container-high/50"><div className="relative grid h-20 w-28 shrink-0 overflow-hidden rounded border border-surgical-steel bg-surface-container-lowest text-fog-muted"><div className="absolute inset-0 opacity-45 [background-image:linear-gradient(rgba(78,222,163,0.35)_1px,transparent_1px),linear-gradient(90deg,rgba(78,222,163,0.35)_1px,transparent_1px)] [background-size:16px_16px]" />{course.thumbnailVideoId && <video aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-80" src={`/api/courses/videos/${course.thumbnailVideoId}/stream`} muted playsInline preload="metadata" />}{course.isCompleted ? <CheckCircle2 size={21} className="relative z-10" /> : <span className="relative z-10 grid size-9 place-items-center rounded-full border border-primary-container/50 bg-surface/85 text-primary-container transition group-hover:scale-110"><Play size={15} fill="currentColor" /></span>}<span className="absolute bottom-1.5 left-1.5 z-10 rounded bg-surface/90 px-1.5 py-1 font-label text-[9px] uppercase tracking-wider text-white">{course.totalVideos} lessons</span></div><div className="min-w-0 flex-1"><div className="flex items-baseline justify-between gap-3"><p className="truncate text-sm font-semibold text-white group-hover:text-primary-container">{course.title}</p><span className="shrink-0 font-label text-xs text-primary-container">{course.isCompleted ? "Complete" : `${course.progress}%`}</span></div><p className="mt-1 text-xs text-fog-muted">{course.isCompleted ? "Course completed · ready to review" : `${course.completedVideos} of ${course.totalVideos} lessons complete · ${course.remainingMinutes} min remaining`}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-surface-container-highest"><div className="h-full rounded-full bg-primary-container transition-[width] duration-500" style={{ width: `${course.progress}%` }} /></div></div>{course.isCompleted ? <CheckCircle2 size={16} className="shrink-0 text-primary-container" /> : <ArrowRight size={16} className="shrink-0 text-fog-muted transition group-hover:translate-x-1 group-hover:text-primary-container" />}</Link>; }
