"use client";

import { useActionState } from "react";
import { CalendarClock, LoaderCircle, LogOut, RotateCcw, ShieldAlert } from "lucide-react";

import { cancelAccountDeletion, EMPTY_SETTINGS_ACTION_STATE, logoutAction } from "@/app/dashboard/settings/actions";

export function DeletionPendingScreen({ name, scheduledAt, status }: { name: string; scheduledAt: string; status: string }) {
  const [state, action, pending] = useActionState(cancelAccountDeletion, EMPTY_SETTINGS_ACTION_STATE);
  const canCancel = status === "pending";
  return <main className="grid min-h-svh place-items-center bg-surface px-4 py-10 text-on-surface"><section className="w-full max-w-2xl overflow-hidden rounded-2xl border border-surgical-steel bg-monolith-surface shadow-[0_24px_70px_-34px_rgba(0,0,0,0.9)]"><div className="border-b border-surgical-steel bg-surface-container-low px-6 py-5 sm:px-8"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full border border-error/40 bg-error/10 text-error"><ShieldAlert size={19}/></span><div><p className="text-sm font-semibold text-white">Stoicverse account</p><p className="text-xs text-fog-muted">Deletion recovery</p></div></div></div><div className="px-6 py-8 sm:px-8 sm:py-10"><h1 className="text-3xl font-semibold tracking-[-0.025em] text-white">Your account is scheduled for deletion</h1><p className="mt-4 max-w-xl text-sm leading-6 text-on-surface-variant">{name}, dashboard access is locked while this request is active. Your account will be permanently removed after the recovery window unless you cancel.</p><div className="mt-7 flex items-start gap-4 border-y border-surgical-steel py-5"><CalendarClock size={20} className="mt-0.5 shrink-0 text-primary-container"/><div><p className="text-sm font-semibold text-white">Scheduled deletion</p><p className="mt-1 text-sm text-on-surface-variant">{new Intl.DateTimeFormat(undefined, { dateStyle: "full", timeStyle: "short" }).format(new Date(scheduledAt))}</p></div></div>{status === "failed" && <p role="alert" className="mt-6 border border-error/35 bg-error/10 p-4 text-sm leading-6 text-error">Automatic deletion needs administrator attention. Your data remains locked and intact; contact support for recovery or completion.</p>}<div className="mt-7 flex flex-col gap-3 sm:flex-row">{canCancel && <form action={action}><button type="submit" disabled={pending} className="focus-ring inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-full bg-primary-container px-5 text-sm font-semibold text-on-primary-fixed transition hover:brightness-105 disabled:opacity-50">{pending ? <LoaderCircle size={16} className="animate-spin"/> : <RotateCcw size={16}/>}Cancel deletion</button></form>}<form action={logoutAction}><button type="submit" className="focus-ring inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-full border border-surgical-steel px-5 text-sm font-semibold text-on-surface transition hover:border-primary-container hover:text-primary-container"><LogOut size={16}/>Log out</button></form></div>{state.error && <p role="alert" className="mt-4 text-sm text-error">{state.error}</p>}<p className="mt-7 text-xs leading-5 text-fog-muted">If deletion completes, community discussions are preserved under “Deleted member” while personal profile and learning records are removed.</p></div></section></main>;
}
